packages:
  - .
  - lib/**

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild

# only allow 14+ day old package releases - helps somewhat against supply chain attacks
minimumReleaseAge: 20160

allowBuilds:
  '@swc/core': true
  esbuild: true
